### ISSUE TITLE
Servarr Lookups No Longer Working from IMDB

### ISSUE THREAD

**Issue by ekk88d** [trossr32/sonarr-radarr-lidarr-autosearch-browser-extension#47]
This extension was working perfectly, but neither Sonarr nor Radarr work from the extension's search icon via IMDB.

I'm using V3 of Sonarr and Radarr on my LAN's HTPC. Everything was working fine, connecting to the local LAN IP, with the V3 Advanced integration settings.
Maybe something changed with Servarr V3 jquery selectors. I can't find anything different with the search path.

In the extension's settings, I turned on Debug console, but I'm not sure where to look for that debug console or its log.

**Comment by trossr32** [comment]
Thanks for the update, I really need to find some time to update the
project but have been snowed under with work recently. Will try to sort
this weekend 👍

**Comment by ekk88d** [comment]
> Thanks for the update, I really need to find some time to update the project but have been snowed under with work recently. Will try to sort this weekend 👍

I appreciate that. Your extension is exactly what is needed for Servarr programs in Chrome.

**Comment by daneyuleb** [comment]
I also get a white screen when searching on imdb.  And... not sure how the console logging should work or I'd send a bug report.

**Comment by trossr32** [comment]
IMDb integration is working for me. Release v2 going out once approved, hopefully this fixes the issue but if not please get back in touch and I'll try to duplicate your environment and replicate the issue.

**Comment by trossr32** [comment]
@daneyuleb the console logging toggle simply outputs debug logs to the browser console and is unlikely to be helpful to you unless you know what you're looking for. See previous comment. Once you're updated to v2, please retest and let me know if issues continue.

**Comment by trossr32** [comment]
V2 now available on all supported browsers. I'll leave this ticket open for a few days and if there's no update it'll be closed.

**Comment by ekk88d** [comment]
When I tried testing Sonarr and Radarr, at first, it timed out. Then, I changed both Sonarr and Radarr >> Settings >> General >> Certificate Validation to "Disabled for Local Addresses."

That made Radarr start working, immediately. Sonarr, however, still times out. I double-checked the port, don't use an URL base and the extension is pointed to my HTPC's LAN address.

It's strange that Radarr works, but Sonarr doesn't. The search settings even auto-populated for Sonarr, in the extension's advanced tab.

**Comment by trossr32** [comment]
@ekk88d let me try to duplicate your environment here. Can you provide me with:

- Sonarr version
- Whether your LAN address for your HTPC is using https or http (assume https if you've played with the cert validation settings?)
- Might also be worth supplying the link to the IMDb page that you're using for testing.

I usually test different Sonarr versions by spinning them up in docker and use http protocol.

I have a feeling this is going to be an issue outside the scope of the extension, but will try to help.

**Comment by ekk88d** [comment]
Great, thanks Rob:

   - Sonarr version is 3.0.6.1272 w/.NET version 4.8.0. It's on the develop
   branch and I think it was auto-updated again, today.
   - LAN address is only using HTTP, because I figured HTTPS is tied to the
   SSL toggle in Sonarr/Radarr settings. SSL is off, so I always use HTTP.
   Even with it off, Radarr only worked after I changed that Cert Validation
   setting.
   - The IMDB page that I was using was the first one I grabbed from their
   homepage: https://www.imdb.com/title/tt9140554

**Comment by daneyuleb** [comment]
Thanks for the response Trossr32!  

Upgrading to v2 got rid of the white screen, thanks!   

I then got a 404 site not found when using IMDB for Radar, but  "**Radarr >> Settings >> General >> Certificate Validation to "Disabled for Local Addresses.**" immediately fixed and it works fine now!

Wonderful product!!  Hate the name though--hard to search for and to remember! And _limiting_. 

It's a good, useful app. You should call it something more catchy, like "Downloadinator 4000"... or "Bob"... or "This here thingee I done made".  Anything's better and more memorable (and more searchable) than:  "Sonar, Radarr Lidar Autosearch Browser Extension.{  

-Daniel

**Comment by ekk88d** [comment]
@daneyuleb

Glad you got Radarr working! Do you use Sonarr?
If so, did you get it working with trossr32's V2 extension update?

Looks like you got the exact same workaround that I used. Did you get it
from my troubleshooting comment or stumble upon the extension's Radar
connectivity fix?

I'm asking if you tried other things, because I'd try them with Sonarr,
since I still can't get it to work.

That setting was Enabled, by default, but I didn't see any harm with easing
up for one's own LAN access to these apps.

Cheers

**Comment by trossr32** [comment]
@daneyuleb Domwloadinator 4000 really made me laugh, thanks for that!

**Comment by daneyuleb** [comment]
@ekk88d Sorry, I should have credited you, because, yes, I got the fix from your comment. So... thanks!!!  I use Sonarr, but haven't used it with this app (don't really have the need) but I'll give it a try and see if I get the same thing.

@trossr32 😊😊😊

**Comment by trossr32** [comment]
@ekk88d when you see this error, are there any errors showing in the browsers developer console? (F12 usually opens up dev tools, then look at the console tab)

**Comment by daneyuleb** [comment]
For what it's worth, I'm using an older Sonarr (Sonarr Ver. 2.0.0.5344) and this extension works fine for me with no changes. (In this version of Sonarr, I don't even have the " Settings >> General >> Certificate Validation" option available.  I may update to the v3 release of Sonarr soon and if it breaks things I'll report back.

**Comment by ekk88d** [comment]
@trossr32 Ok, I was getting a generic Timed Out error in Console, so I did some more sporadic digging.
Finally, I found the solution on an old Sonarr network connectivity reddit thread.

I did two things. One or both fixed the Sonarr test connectivity issue:

1.  On the machine that hosts Sonarr, I opened an admin-level command prompt and typed
`netsh http add iplisten <local LAN IP address>`
In my case the IP address for that command was 192.168.1.106
2.  Disabled _World Wide Web Publishing_ service in _Run >> services.msc_

Then, I ran the Sonarr test in the Chrome extension and it immediately connected successfully.
Radarr was already working, but I wanted to check on the _Certificate Validation_ option. For both Sonarr and Radarr, I went to _Settings >> General >> Certificate Validation_ and changed the dropdown back to _Enabled_. Everything still works as it should.

I hope that these steps help more people get this extension going and it's great material for its wiki. In case anyone else wants to append comments to this issue thread, I'll leave it open, so feel free to close it.

Lastly, these other Sonarr network connectivity suggestions didn't work for me, but could work for someone else:
- Create a Windows Firewall rule to allow inbound traffic for the Sonarr (or Radarr) program. Sonarr's exe is usually found in:
`C:\ProgramData\Sonarr\bin`
- Shutdown Sonarr (or Radarr) Go through the start menu to find the Sonarr program's shortcut. Right-click the icon and _Run as administrator._

**Comment by ekk88d** [comment]
Update:

I'm not sure if this is related, but the TV series' name/ID doesn't get passed to Sonarr using the extension. I tried using both TVCal and IMDB. The search box just remains blank. Radarr gets the info just fine.

In comparing both the Sonarr vs Radarr consoles on the extension's resulting search page, I found that the blank Sonarr search's page conole lacked this output:

```
[signalR] starting instrument.js:109
[signalR] Information: Normalizing '/signalr/messages?access_token=(removed)' to 'http://10.10.10.6:7878/signalr/messages?access_token=(removed)'.
```
This info was present on the Radarr output page, but missing on the Sonarr page that had a blank search entry

If this is better suited for a new issue thread let me know.

**Comment by trossr32** [comment]
Hi,

Apologies for the delay in responding to this thread, but my RAID in my NAS threw a hissy fit and it's taken me a while to rebuild everything. On the plus side, I'm now running Sonarr and Radarr in docker containers rather than using native applications on the NAS, so I can mirror most people's environments more easily.

It appears that the issues being faced are fixed. I have however run into an issue using v3 or Radarr & Sonarr which was that occasionally the search input wasn't always populated with the search string or id.

The extension tries tom find the search element on the page using a waiting method, and it was configured at 1 second (10 attempts as 100ms intervals). It seems this wasn't always long enough for the Servarr UI to load and the element be rendered.

To fix this I've done a few things:

1. I've extended the default timeout as 6 seconds (20 attempts at 300ms intervals)
2. When debug logging is enabled, messages showing how long the element took to load are displayed:

![image](https://user-images.githubusercontent.com/332954/127778838-cbf90a90-88f0-4a9c-a88b-c9fadf816c4f.png)

3. If the search input is not found, display an error message (this occurs regardless of the debug logging being enabled or not)

![image](https://user-images.githubusercontent.com/332954/127778864-ef5baf21-c34e-4678-88e3-0370d538ac13.png)

4. Added UI to the debug settings tab that allows these values to be configured, so if anyone's seeing issues you can try to increase the wait time. I'd be surprised if 6 seconds isn't enough though.

![image](https://user-images.githubusercontent.com/332954/127778913-64472f4c-3123-4ef8-9b3a-0268c3d409d3.png)

These fixes/features will be going out with the next release. I have a couple of other issues I'd like to include too so it might not go out for a few days.

I'll leave this issue open for now but will look to close after the next release.

**Comment by ekk88d** [comment]
Just swinging back into this thread to let you know that everything is fixed, so this can get Closed.
Thanks for fixing and that documentation.

One thing:
I noticed that Sonarr lookups search by the IMDB page's title. Some series' titles are overused, so they generate numerous extra Sonarr search results.
If you can include the series' debut year in the Sonarr search string, it's helped me with search accuracy in the past.

**Comment by ekk88d** [comment]
Sonarr's _Search by IMDB ID_ feature is still missing and searching only by title can get messy.
Instead of opening a new thread here about a Sonarr feature, I just wanted to append my OP with the Sonarr issue's link.
Post here:
[Sonarr Issue 1829](https://www.github.com/Sonarr/Sonarr/issues/1829)
